/**
 * app/(app)/referral.tsx
 * Institutional Affiliate Network Hub
 */
import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, SafeAreaView, ScrollView, Share, Alert, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuthStore } from '../../lib/authStore';
import { usePortfolio } from '../../hooks/usePortfolio';

export default function ReferralScreen() {
  const { user } = useAuthStore();
  const { portfolio } = usePortfolio();

  // Fallback if code isn't in state yet
  const refCode = user?.referral_code || 'DNX-PENDING';
  const refLink = `https://app.dunexmarkets.com/register?ref=${refCode}`;

  const copyToClipboard = async () => {
    await Share.share({
      message: `Join me on Dunex Markets, the institutional wealth platform. Use my invite code: ${refCode}\n${refLink}`,
    });
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView style={styles.container} contentContainerStyle={{ padding: 24 }}>
        
        <View style={styles.header}>
          <Ionicons name="git-network" size={32} color="#A855F7" style={{ marginBottom: 12 }} />
          <Text style={styles.title}>Affiliate Network</Text>
          <Text style={styles.subtitle}>Invite high-net-worth individuals to Dunex and earn perpetual commissions on their portfolio yield.</Text>
        </View>

        {/* Network Earnings Card */}
        <View style={styles.balanceCard}>
          <Text style={styles.balanceLabel}>TOTAL NETWORK EARNINGS</Text>
          <Text style={styles.balanceAmount}>${portfolio.balances.referral.toLocaleString('en-US', { minimumFractionDigits: 2 })}</Text>
          <Text style={styles.balanceSub}>Available for immediate withdrawal</Text>
        </View>

        {/* Invite Code Box */}
        <Text style={styles.sectionLabel}>YOUR INVITATION CODE</Text>
        <View style={styles.codeCard}>
          <Text style={styles.codeText}>{refCode}</Text>
          <TouchableOpacity style={styles.copyBtn} onPress={copyToClipboard}>
            <Ionicons name="copy-outline" size={20} color="#05050A" />
            <Text style={styles.copyBtnText}>SHARE LINK</Text>
          </TouchableOpacity>
        </View>

        {/* Tiers / Info */}
        <View style={styles.infoCard}>
          <View style={styles.infoRow}>
            <Ionicons name="star" size={20} color="#D4AF37" />
            <View style={{ marginLeft: 12, flex: 1 }}>
              <Text style={styles.infoTitle}>Tier 1 Commission</Text>
              <Text style={styles.infoDesc}>Earn 10% of trading fees and deposit bonuses generated by your direct invites.</Text>
            </View>
          </View>
        </View>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#05050A' },
  container: { flex: 1 },
  header: { marginBottom: 32, marginTop: 10 },
  title: { color: '#FFFFFF', fontSize: 28, fontWeight: '900', letterSpacing: -0.5, marginBottom: 8 },
  subtitle: { color: '#8E8E93', fontSize: 13, lineHeight: 20 },
  
  balanceCard: { backgroundColor: '#12121A', borderRadius: 20, padding: 24, marginBottom: 32, borderWidth: 1, borderColor: '#1E1E28', alignItems: 'center' },
  balanceLabel: { color: '#A855F7', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 8 },
  balanceAmount: { color: '#FFFFFF', fontSize: 36, fontWeight: '900', fontVariant: ['tabular-nums'], letterSpacing: -1 },
  balanceSub: { color: '#636366', fontSize: 11, marginTop: 8 },

  sectionLabel: { color: '#8E8E93', fontSize: 11, fontWeight: '900', letterSpacing: 1.5, marginBottom: 12, marginLeft: 4 },
  codeCard: { backgroundColor: '#12121A', borderRadius: 16, padding: 20, borderWidth: 1, borderColor: '#1E1E28', marginBottom: 32, alignItems: 'center' },
  codeText: { color: '#FFFFFF', fontSize: 28, fontWeight: '900', letterSpacing: 2, marginBottom: 20, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
  copyBtn: { flexDirection: 'row', backgroundColor: '#A855F7', paddingVertical: 14, paddingHorizontal: 24, borderRadius: 12, alignItems: 'center', gap: 8, width: '100%', justifyContent: 'center' },
  copyBtnText: { color: '#05050A', fontWeight: '900', fontSize: 13, letterSpacing: 1 },

  infoCard: { backgroundColor: '#12121A', borderRadius: 16, padding: 20, borderWidth: 1, borderColor: '#1E1E28' },
  infoRow: { flexDirection: 'row', alignItems: 'flex-start' },
  infoTitle: { color: '#FFFFFF', fontSize: 14, fontWeight: '700', marginBottom: 4 },
  infoDesc: { color: '#8E8E93', fontSize: 12, lineHeight: 18 },
});